name: flutter_practice
description: A new Flutter project.
publish_to:

version: 1.0.0+1

environment:
  sdk: '>=2.19.3 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.2.6
  path_provider: ^2.0.14
  path: ^1.8.2
  intl: ^0.17.0
  http: ^0.13.5
  provider: ^6.0.5
  shared_preferences: ^2.1.0
  cupertino_icons: ^1.0.2
  firebase_database: ^10.1.0
  dio: ^5.1.1
  firebase_core: ^2.9.0
  camera: ^0.10.3+2
  transparent_image: ^2.0.1
  image_picker: ^0.8.7+1
  location: ^2.3.5
  firebase_auth: ^4.4.0
  google_sign_in: ^6.1.0
  flutter_signin_button: ^2.0.0
  hive: ^2.1.0
  hive_flutter: ^1.1.0
  flutter_secure_storage: ^8.0.0
  hive_generator: ^2.0.0
  cloud_firestore: ^4.5.0
  google_sign_in_web: ^0.12.0
  country_code_picker: ^2.0.2
  url_launcher: ^6.0.20
  equatable: ^2.0.3
  firebase_storage: ^11.1.0
  fluttertoast: ^8.2.1
  firebase_messaging: ^14.4.0
  flutter_local_notifications: ^13.0.0
  permission_handler: ^10.2.0
  battery: ^2.0.3




dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.1.8


flutter:

  uses-material-design: true

  assets:
  - assets/images/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Black.ttf
        - asset: assets/fonts/Roboto-Italic.ttf
          style: italic
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700

